"""Ingest a human-written operation manual into the two-layer knowledge base.

A manual describes ONE platform's UI & operations — the same app on iPhone vs browser vs
Android navigates differently — so a manual is ingested **for a target platform** and lands
under ``knowledge/<platform>/<app>/``. Only the INJECTION PLUMBING is platform-neutral (the
``set_app_knowledge`` path in ``core/``); the knowledge CONTENT is platform-specific, and
``auto_discover_knowledge(goal, platform)`` only loads it for matching runs of that platform.

Pipeline (mirrors the iPhone recon → summary flow exactly):

    manual ──produce per-"page" knowledge .md── ▶ generate_summary ──▶ _app.md + _elements.md

- **PDF** (image-heavy product manuals): handed to ``manual_pdf.parse_pdf_to_pages`` — segmented
  by its numbered outline (1.1 / 2.3 …) and read by a VISION LLM so the annotated screenshots
  (red boxes / arrows / callouts), which plain text extraction drops, are captured. One .md per
  section.
- **Markdown / txt** (already textual): written as a single page-knowledge file.

Either way the per-page files are then reduced by the existing
``app_summary.generate_summary`` — no bespoke reduce — into _app.md (navigation) + _elements.md
(elements). Offline by design: run once, cached to disk; the runtime auto-discovery path is
untouched.

Usage:
    uv run python -m gui_agent.core.self_learning.manual_ingest \
        "Robo Team 使用说明书.pdf" browser RoboTeam
    # 测试:只解析前 N 页
    uv run python -m gui_agent.core.self_learning.manual_ingest \
        "Robo Team 使用说明书.pdf" browser RoboTeam --max-pages 5
"""

from __future__ import annotations

import argparse
import re
import unicodedata
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from gui_agent.core.self_learning.app_summary import (
    KNOWLEDGE_DIR,
    AppKnowledge,
    generate_summary,
)

_HEADING = re.compile(r"^(#{1,6})\s+(.*\S)\s*$")


def split_markdown_sections(text: str) -> list[tuple[str, str]]:
    """Split a markdown manual into (title, body) sections at its shallowest recurring heading.

    A textual manual is ONE blob, but the runtime wants per-section page files (like the PDF path
    and RoboTeam) so KnowledgeSelector can progressively load only the relevant section. We split
    at the **shallowest heading level that occurs ≥2 times**: a single-H1-title + H2-chapters manual
    splits on H2; a concatenation of docs each owning an H1 splits on H1. Content before the first
    boundary heading is the manual's title/intro (not a retrievable section) and is dropped. Empty
    sections are dropped. No headings at all → the whole text becomes one section.
    """
    lines = text.splitlines()
    counts: dict[int, int] = {}
    for ln in lines:
        m = _HEADING.match(ln)
        if m:
            counts[len(m.group(1))] = counts.get(len(m.group(1)), 0) + 1
    if not counts:
        return [("manual", text.strip())] if text.strip() else []
    recurring = [lvl for lvl in sorted(counts) if counts[lvl] >= 2]
    split_lvl = recurring[0] if recurring else sorted(counts)[0]

    sections: list[tuple[str, str]] = []
    title: Optional[str] = None
    body: list[str] = []
    for ln in lines:
        m = _HEADING.match(ln)
        if m and len(m.group(1)) == split_lvl:
            if title is not None:
                sections.append((title, "\n".join(body).strip()))
            title, body = m.group(2).strip(), []
        elif title is not None:
            body.append(ln)
        # else: preamble before the first boundary heading → dropped
    if title is not None:
        sections.append((title, "\n".join(body).strip()))
    return [(t, b) for t, b in sections if b]


def load_manual_text(path: Path) -> str:
    """Extract plain text from a textual manual (.md / .txt / .pdf-as-text fallback).

    All text is NFKC-normalized, folding the CJK compatibility / Kangxi-radical glyphs that PDF
    extraction often emits (``⽤``→``用``, ``⻚``→``页``). Used for the Markdown/txt path; PDFs go
    through the vision pipeline in ``manual_pdf`` instead.
    """
    suffix = path.suffix.lower()
    if suffix == ".pdf":
        import pypdf

        reader = pypdf.PdfReader(str(path))
        parts = [(p.extract_text() or "").strip() for p in reader.pages]
        text = "\n\n".join(t for t in parts if t)
    elif suffix in (".md", ".markdown", ".txt"):
        text = path.read_text(encoding="utf-8")
    else:
        raise ValueError(f"不支持的手册格式: {suffix}(支持 .pdf / .md / .txt)")
    return unicodedata.normalize("NFKC", text).strip()


def _clear_page_files(app_dir: Path) -> None:
    """Remove stale page-knowledge files (keep _app.md/_elements.md, regenerated by reduce)."""
    for md in app_dir.glob("*.md"):
        if not md.name.startswith("_"):
            md.unlink()


def ingest_manual(
    manual_path: Path,
    platform: str,
    app: str,
    max_pages: Optional[int] = None,
) -> AppKnowledge:
    """Ingest a manual into knowledge/<platform>/<app>/: produce page knowledge, then reduce.

    ``max_pages`` (PDF only) limits parsing to a leading page range — for quick tests.
    """
    if not manual_path.exists():
        raise FileNotFoundError(f"手册文件不存在: {manual_path}")
    app_dir = KNOWLEDGE_DIR / platform / app
    app_dir.mkdir(parents=True, exist_ok=True)
    _clear_page_files(app_dir)

    suffix = manual_path.suffix.lower()
    if suffix == ".pdf":
        from gui_agent.core.self_learning.manual_pdf import parse_pdf_to_pages

        print(f"解析 PDF 手册 {manual_path.name} → platform={platform}, app={app}"
              + (f"(前 {max_pages} 页)" if max_pages else ""))
        n = parse_pdf_to_pages(manual_path, app_dir, max_pages=max_pages)
        if n == 0:
            raise ValueError(f"未从 {manual_path.name} 解析出任何编号小节(检查手册是否带 N.N 编号大纲)")
        print(f"  得到 {n} 个小节页知识 → {app_dir}")
    elif suffix in (".md", ".markdown", ".txt"):
        # Markdown/txt manuals are split into per-section page files (heading-delimited) so they
        # feed the same per-section progressive-load path as the PDF flow and RoboTeam — NOT a
        # single monolithic blob (which would defeat KnowledgeSelector).
        from gui_agent.core.self_learning.manual_pdf import _safe_name

        text = load_manual_text(manual_path)
        if not text:
            raise ValueError(f"未能从 {manual_path.name} 读到文字")
        sections = split_markdown_sections(text)
        if not sections:
            raise ValueError(f"未从 {manual_path.name} 切出任何章节(检查手册是否有 Markdown 标题)")
        used: set[str] = set()
        for title, body in sections:
            name = _safe_name(title)
            if name in used:  # 重名兜底(标题撞名),加序号区分
                k = 2
                while f"{name}_{k}" in used:
                    k += 1
                name = f"{name}_{k}"
            used.add(name)
            (app_dir / f"{name}.md").write_text(f"# {title}\n\n{body}", encoding="utf-8")
        print(f"文本手册 {manual_path.name} ({len(text)} 字) → {len(sections)} 个章节页知识 → {app_dir}")
    else:
        raise ValueError(f"不支持的手册格式: {suffix}(支持 .pdf / .md / .txt)")

    # 顺产检索描述:每节生成一行 when:(何时查阅)frontmatter,供 KnowledgeSelector 清单做同物异名
    # 桥接(标题字面与任务用词不一致时,纯标题清单会选错章节)。两条路径都产章节,统一在此生成。
    from gui_agent.core.self_learning.gen_when import generate_for_app

    generate_for_app(app, platform)

    # 复用既有归约:每页知识 → _app.md(导航层)。章节文件已是 progressive 检索的主体,_elements.md
    # 仅作无章节时的回退,手册摄入恒产章节,故跳过(省一次 LLM 归约,且与 RoboTeam 形态一致)。
    return generate_summary(app, platform, make_elements=False)


def main() -> None:
    load_dotenv()
    parser = argparse.ArgumentParser(
        description="把操作手册(PDF/Markdown)解析成两层知识库写入 knowledge/<平台>/<app>/,"
        "供 auto_discover_knowledge 在该平台运行时按 app 名匹配注入。"
    )
    parser.add_argument("manual", type=Path, help="手册文件路径(.pdf / .md / .txt)")
    parser.add_argument(
        "platform",
        choices=["iphone", "browser", "android"],
        help="手册所属平台(决定 knowledge/<平台>/ 子目录,只在该平台运行时被注入)",
    )
    parser.add_argument(
        "app",
        help="应用名,决定 knowledge/<平台>/<app>/ 目录;须能在任务目标文本里被匹配到(如 RoboTeam)",
    )
    parser.add_argument(
        "--max-pages",
        type=int,
        default=None,
        help="(仅 PDF)只解析前 N 页,用于快速测试",
    )
    args = parser.parse_args()
    ingest_manual(args.manual, args.platform, args.app, max_pages=args.max_pages)


if __name__ == "__main__":
    main()
